language: php
 
php:
    - 7.1

before_script:
    - cp .env.travis .env
    - mysql -e 'create database homestead_test;'
    - composer self-update
    - composer install
    - php artisan key:generate
 
script:
    - vendor/bin/phpunit

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor 
 
notifications:
    email: false

